import { StyleSheet } from "react-native";
import { colors, font, radius, shadow, spacing } from "../../constants/Theme";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.xl,
    gap: spacing.lg,
  },
  screenWrapper: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenContent: {
    padding: spacing.xl,
    gap: spacing.lg,
  },
  notificationCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.blue100,
    boxShadow: shadow.md.boxShadow,
    elevation: shadow.md.elevation,
    gap: spacing.md,
  },
  notificationKicker: {
    color: colors.blue500,
    fontSize: font.size.xs,
    fontWeight: font.weight.semibold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  notificationTitle: {
    color: colors.gray900,
    fontSize: font.size.lg,
    fontWeight: font.weight.bold,
  },
  notificationBody: {
    color: colors.gray500,
    fontSize: font.size.sm,
    lineHeight: 20,
  },
  tokenOutputBox: {
    width: "100%",
    backgroundColor: colors.gray50,
    padding: spacing.md,
    borderRadius: radius.md,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.xs,
  },
  tokenLabel: {
    fontSize: font.size.xs,
    fontWeight: font.weight.semibold,
    color: colors.gray700,
    textTransform: "uppercase",
  },
  tokenDataStream: {
    fontFamily: font.family.mono,
    fontSize: font.size.xs,
    color: colors.blue900,
  },
  waitingText: {
    fontSize: font.size.sm,
    color: colors.amber500,
    fontStyle: "italic",
  },
  headerCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.borderLight,
    boxShadow: shadow.md.boxShadow,
    elevation: shadow.md.elevation,
    gap: spacing.lg,
  },
  headerCopy: {
    gap: spacing.sm,
  },
  kicker: {
    color: colors.blue500,
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  title: {
    color: colors.gray900,
    fontSize: font.size.xxl,
    fontWeight: font.weight.bold,
  },
  subtitle: {
    color: colors.gray500,
    fontSize: font.size.md,
    lineHeight: 22,
  },
  statusChip: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.green50,
    borderColor: colors.green100,
    borderWidth: 1,
    borderRadius: radius.full,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  statusDot: {
    width: 10,
    height: 10,
    borderRadius: 10,
    backgroundColor: colors.green500,
  },
  statusText: {
    color: colors.green900,
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
  },
  metricsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  metricCard: {
    width: "48%",
    minHeight: 132,
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.borderLight,
    boxShadow: shadow.sm.boxShadow,
    elevation: shadow.sm.elevation,
    justifyContent: "space-between",
  },
  metricLabel: {
    fontSize: font.size.sm,
    fontWeight: font.weight.semibold,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  metricValue: {
    color: colors.gray900,
    fontSize: font.size.xxl,
    fontWeight: font.weight.bold,
  },
  metricDetail: {
    color: colors.gray500,
    fontSize: font.size.sm,
    lineHeight: 18,
  },
  progressCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.borderLight,
    boxShadow: shadow.md.boxShadow,
    elevation: shadow.md.elevation,
    gap: spacing.md,
  },
  sectionTitle: {
    color: colors.gray900,
    fontSize: font.size.lg,
    fontWeight: font.weight.bold,
  },
  progressTrack: {
    height: 12,
    borderRadius: radius.full,
    backgroundColor: colors.surfaceAlt,
    overflow: "hidden",
  },
  progressFill: {
    width: "72%",
    height: "100%",
    borderRadius: radius.full,
    backgroundColor: colors.blue500,
  },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  progressText: {
    flex: 1,
    color: colors.gray700,
    fontSize: font.size.md,
  },
  progressValue: {
    color: colors.gray900,
    fontSize: font.size.md,
    fontWeight: font.weight.semibold,
  },
  footerCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.borderLight,
    boxShadow: shadow.md.boxShadow,
    elevation: shadow.md.elevation,
    gap: spacing.lg,
  },
  footerTitle: {
    color: colors.gray900,
    fontSize: font.size.lg,
    fontWeight: font.weight.bold,
  },
  footerSubtitle: {
    color: colors.gray500,
    fontSize: font.size.sm,
    lineHeight: 20,
    marginTop: spacing.xs,
  },
  logoutButton: {
    minHeight: 48,
    borderRadius: radius.lg,
    backgroundColor: colors.red500,
    alignItems: "center",
    justifyContent: "center",
  },
  logoutText: {
    color: colors.white,
    fontSize: font.size.md,
    fontWeight: font.weight.semibold,
  },
});
